//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABCDemo2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class myOpDBEntities : DbContext
    {
        public myOpDBEntities()
            : base("name=myOpDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblArticoli> tblArticoli { get; set; }
        public virtual DbSet<tblArticoliPrezzi> tblArticoliPrezzi { get; set; }
        public virtual DbSet<tblArticoliQualifiche> tblArticoliQualifiche { get; set; }
        public virtual DbSet<tblInvestimenti> tblInvestimenti { get; set; }
        public virtual DbSet<tblQualifiche> tblQualifiche { get; set; }
        public virtual DbSet<tblUtenti> tblUtenti { get; set; }
        public virtual DbSet<tblUtentiArticoliQualifiche> tblUtentiArticoliQualifiche { get; set; }
        public virtual DbSet<tblVendite> tblVendite { get; set; }
    }
}
