//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABCDemo2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblArticoli
    {
        public tblArticoli()
        {
            this.tblArticoliQualifiche = new HashSet<tblArticoliQualifiche>();
            this.tblInvestimenti = new HashSet<tblInvestimenti>();
            this.tblArticoliPrezzi = new HashSet<tblArticoliPrezzi>();
        }
    
        public int IDArticolo { get; set; }
        public string CodiceArticolo { get; set; }
        public string DescrizioneArticolo { get; set; }
        public string WebLinkArticolo { get; set; }
    
        public virtual ICollection<tblArticoliQualifiche> tblArticoliQualifiche { get; set; }
        public virtual ICollection<tblInvestimenti> tblInvestimenti { get; set; }
        public virtual ICollection<tblArticoliPrezzi> tblArticoliPrezzi { get; set; }
    }
}
