//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABCDemo2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblArticoliPrezzi
    {
        public tblArticoliPrezzi()
        {
            this.tblVendite = new HashSet<tblVendite>();
        }
    
        public int IDArticoloPrezzo { get; set; }
        public Nullable<int> IDArticolo { get; set; }
        public string TipoPrezzo { get; set; }
        public Nullable<decimal> Prezzo { get; set; }
        public string DescrizionePrezzo { get; set; }
    
        public virtual tblArticoli tblArticoli { get; set; }
        public virtual ICollection<tblVendite> tblVendite { get; set; }
    }
}
