//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABCDemo2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblArticoliQualifiche
    {
        public tblArticoliQualifiche()
        {
            this.tblUtentiArticoliQualifiche = new HashSet<tblUtentiArticoliQualifiche>();
        }
    
        public int IDArticoloQualifica { get; set; }
        public Nullable<int> IDArticolo { get; set; }
        public Nullable<int> IDQualifica { get; set; }
        public Nullable<decimal> Percentuale { get; set; }
    
        public virtual tblArticoli tblArticoli { get; set; }
        public virtual tblQualifiche tblQualifiche { get; set; }
        public virtual ICollection<tblUtentiArticoliQualifiche> tblUtentiArticoliQualifiche { get; set; }
    }
}
