//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABCDemo2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblInvestimenti
    {
        public int IDInvestimento { get; set; }
        public Nullable<int> IDUtente { get; set; }
        public Nullable<int> IDArticolo { get; set; }
        public Nullable<System.DateTime> DataInvestimento { get; set; }
        public string Finalita { get; set; }
        public Nullable<decimal> Investimento { get; set; }
    
        public virtual tblArticoli tblArticoli { get; set; }
        public virtual tblUtenti tblUtenti { get; set; }
    }
}
