//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABCDemo2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblQualifiche
    {
        public tblQualifiche()
        {
            this.tblArticoliQualifiche = new HashSet<tblArticoliQualifiche>();
        }
    
        public int IDQualifica { get; set; }
        public string CodiceQualifica { get; set; }
        public string DescrizioneQualifica { get; set; }
    
        public virtual ICollection<tblArticoliQualifiche> tblArticoliQualifiche { get; set; }
    }
}
