//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABCDemo2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUtenti
    {
        public tblUtenti()
        {
            this.tblInvestimenti = new HashSet<tblInvestimenti>();
            this.tblUtentiArticoliQualifiche = new HashSet<tblUtentiArticoliQualifiche>();
        }
    
        public int IDUtente { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public Nullable<System.DateTime> DataInserimento { get; set; }
        public string NomeUtente { get; set; }
        public string CognomeUtente { get; set; }
        public string RagioneSociale { get; set; }
        public string IndirizzoSedeLegale { get; set; }
        public string CittaSedeLegale { get; set; }
        public string IndirizzoSedeOperativa1 { get; set; }
        public string CittaSedeOperativa1 { get; set; }
        public string IndirizzoSedeOperativa2 { get; set; }
        public string CittaSedeOperativa2 { get; set; }
        public string IndirizzoSedeOperativa3 { get; set; }
        public string CittaSedeOperativa3 { get; set; }
        public string Telefono { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string Pec { get; set; }
        public string SitoWeb { get; set; }
    
        public virtual ICollection<tblInvestimenti> tblInvestimenti { get; set; }
        public virtual ICollection<tblUtentiArticoliQualifiche> tblUtentiArticoliQualifiche { get; set; }
    }
}
